spring:
  application:
    name: local
  datasource:
    url: jdbc:postgresql://localhost:5432/myhome
    username: ywonp94
    password: myhome1572
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect