spring:
  application:
    name: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/myhome
    username: ywonp94
    password: myhome1572
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
  jackson:
    deserialization:
      fail-on-null-for-primitives: true # DTO default값 넣지 않기 위해 추가
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration/dev